- name: Setup Robohsop Project
  hosts: all
  become: yes
  tasks:
    - name: Import Frontend
      ansible.builtin.import_role:
        name: frontend
    - name: Import Catalogue
      ansible.builtin.import_role:
        name: catalogue

