- name: Setup Python {{ COMPONENT }} Component
  include_role:
    name: common
    tasks_from: python
  vars:
    URL: "https://github.com/roboshop-devops-project/payment/archive/main.zip"

- name: Setup Node Exporter
  include_role:
    name: common
    tasks_from: node_exporter

- name: Setup Filebeat
  include_role:
    name: filebeat

