- name: Install ErLang
  yum:
    name: https://github.com/rabbitmq/erlang-rpm/releases/download/v23.2.6/erlang-23.2.6-1.el7.x86_64.rpm
    state: present

- name: Setup YUM repos
  shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Install RabbitMQ Server
  yum:
    name: rabbitmq-server
    state: present

- name: Start RabbitmQ Server
  systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Setup RoboShop User
  #community.rabbitmq.rabbitmq_user:
  rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    tags: administrator

- name: Setup Node Exporter
  include_role:
    name: common
    tasks_from: node_exporter

