- name: Setup NodeJS {{ COMPONENT }} Component
  include_role:
    name: common
    tasks_from: nodejs
  vars:
    APP_USER: roboshop
    APP_PATH: /home/roboshop/catalogue

- name: Setup Node Exporter
  include_role:
    name: common
    tasks_from: node_exporter

- name: Setup Filebeat
  include_role:
    name: filebeat

