- name: Setup NodeJS {{ COMPONENT }} Component
  include_role:
    name: common
    tasks_from: nodejs
  vars:
    URL: "https://github.com/roboshop-devops-project/catalogue/archive/main.zip"

- name: Setup Node Exporter
  include_role:
    name: common
    tasks_from: node_exporter

- name: Setup Filebeat
  include_role:
    name: filebeat

    