filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/{{COMPONENT}}.log
    json.keys_under_root: true
    json.message_key: msg
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1
setup.kibana:
output.elasticsearch:
  hosts: ["172.31.68.6:9200"]

